name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-assume-role-arn:
          type: string
          required: true
      aws-region:
          type: string
          required: true
      aws-s3-bucket-statefile-s3-bucket: 
          type: string
          required: true
      aws-lock-dynamodb-table: 
          type: string
          required: true

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infra
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}
      
      - name: Read destroy configuration
        id: read_destroy_configuration
        run: |
          DESTROY="$(jq -r '.${{ inputs.environment  }}' ./destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

      # - name: Debug backend values
      #   run: |
      #     echo "Bucket: ${{ inputs.aws-s3-bucket-statefile-s3-bucket }}"
      #     echo "Region: ${{ inputs.aws-region }}"
      #     echo "DynamoDB: ${{ inputs.aws-lock-dynamodb-table }}"
          
      - name: Terraform Init
        if: steps.read_destroy_configuration.outputs.destroy != 'true'
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${{ inputs.aws-s3-bucket-statefile-s3-bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=${{ inputs.aws-region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamodb-table }}"

      - name: Terraform Validate
        if: steps.read_destroy_configuration.outputs.destroy != 'true'
        run: terraform validate
      
      - name: Terraform Destroy
        if: steps.read_destroy_configuration.outputs.destroy == 'true'
        run:
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy -var-file="env/${{ inputs.environment }}/terraform.tfvars" -auto-approve

      # - name: Terraform Workspace
      #   run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
        
      # - name: Debug path
      #   run: |
      #     pwd
      #     ls -R

      - name: Create tfvars
        if: steps.read_destroy_configuration.outputs.destroy != 'true'
        working-directory: infra
        run: |
          mkdir -p env/${{ inputs.environment }}
          cat <<EOF > env/${{ inputs.environment }}/terraform.tfvars
          bucket_name = "${{ inputs.environment }}-fabiossena-us-east-1-buildrun-pipeline"
          EOF
                            
      - name: Terraform Plan
        if: steps.read_destroy_configuration.outputs.destroy != 'true'
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform plan \
            -input=false \
            -no-color \
            -var-file="env/${{ inputs.environment }}/terraform.tfvars" \
            -out="${{ inputs.environment }}.plan"

      - name: Terraform Apply
        if: steps.read_destroy_configuration.outputs.destroy != 'true'
        run:
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"

